version: '3.4'

services:
  studybuddy:
    image: studybuddy
    build:
      context: .
      dockerfile: StudyBuddy.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=studybuddydb;Username=studyuser;Password=studypass #FIX AFTER REEALSE DB

  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: studybuddydb
      POSTGRES_USER: studyuser
      POSTGRES_PASSWORD: studypass
    ports:
      - "5432:5432"
